/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * postLogin.java
 *
 * Created on Sep 29, 2013, 7:34:28 PM
 */
package View;

import Model.Client;
import com.mysql.jdbc.EscapeTokenizer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;

/**
 *
 * @author harsh
 */

public class postLogin extends javax.swing.JFrame implements Runnable {
    
    public void run()
    {
        try
        {
            while(remtime>0){
            Thread.sleep(1000);
            remtime--;
            jLabel8.setText(remtime/60+":"+remtime%60);}
        }
        catch(Exception e)
        {
            System.out.println("Thread Exception:"+e);
        }
    }
    /** Creates new form postLogin */
    public postLogin(String handle,int probs,String eventid,String rem) {
        this.setVisible(true);
        this.prob=probs;
        this.eventid=eventid;
        this.handle=handle;
        this.remtime= Long.parseLong(rem);
        remtime/=1000;
        System.out.println("Remtime:"+rem);
        initComponents();
        jLabel8.setText(remtime/60+":"+remtime%60);
        jLabel1.setText("Welcome, "+handle+"!");
        addProblems();
        cl=new Client();
        System.out.println("post login event:"+eventid);
        int i;
        for(i=1;i<=probs;i++)
        requestProblem(i);
        jLabel7.setText("Current Running Event: "+eventid);
        
    }
    private void requestProblem(int probno)
    {
        String req[]=new String[10];
        req[0]="requestProb";
        req[1]=handle;
        req[2]=""+probno;
        req[3]=this.eventid;
        String arr[]=new String[15];
        arr=cl.establishConn(req);
//        System.out.println(arr[2]);
  //      System.out.println(arr[3]);
    //    System.out.println(arr[4]);
        //if(arr==null)
          //  this.dispose();
        probID1[probno-1].setText(arr[1]);
        desLabel1[probno-1].setText(arr[2]);
        timeLabel1[probno-1].setText(arr[3]);
        pointLabel1[probno-1].setText(arr[4]);
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("CopyLeft  :   Harsh Agarwal & Vandit Jain");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LEADERBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel5.setText("My Score:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Contest Time Left:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20));
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(204, 204, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Coder Judge");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 14));
        jLabel7.setText("Current Running Event:");

        jLabel1.setText("Welcome.!");

        jMenu1.setText("Preferences");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void addProblems()
    {
        int i;
        probPanel=new JPanel[prob+2];
        probID=new JLabel[prob+2];
        timeLabel=new JLabel[prob+2];
        pointLabel=new JLabel[prob+2];
        desLabel=new JLabel[prob+2];
        probID1=new JLabel[prob+2];
        timeLabel1=new JLabel[prob+2];
        pointLabel1=new JLabel[prob+2];
        desLabel1=new JTextArea[prob+2];
        fName=new JLabel[prob+2];
        browseFile=new JButton[prob+2];
        submitButton=new JButton[prob+2];
        submitFile=new File[prob+2];
        status=new JLabel[prob+2];
        for(i=0;i<prob;i++)
        {
            probPanel[i]=new JPanel();
            jTabbedPane1.addTab("Problem "+(i+1), null, probPanel[i], "Problem "+i+1);
            probPanel[i].setVisible(true);
            probPanel[i].setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        }
        for(i=0;i<prob;i++)
        probPanel[i].setLayout(null);
        
            
        for(i=0;i<prob;i++)
        {
            probID[i]=new JLabel("Problem ID:");
            probID[i].setBounds(10, 10, 150, 20);
            probID1[i]=new JLabel();
            probID1[i].setBounds(100,10,150,20);
            timeLabel[i]=new JLabel("Time Limit:");
            timeLabel[i].setBounds(200,10, 100, 20);
            timeLabel1[i]=new JLabel();
            timeLabel1[i].setBounds(300,10,50, 20);
            
            pointLabel[i]=new JLabel("Points:");
            pointLabel[i].setBounds(400, 10, 80, 20);
            pointLabel1[i]=new JLabel();
            pointLabel1[i].setBounds(480, 10, 50, 20);
            desLabel[i]=new JLabel("Problem Statement:");
            desLabel[i].setBounds(10, 40, 150, 10);
            desLabel1[i]=new JTextArea();
            desLabel1[i].setEditable(false);
            desLabel1[i].setBackground(Color.LIGHT_GRAY);
            desLabel1[i].setAutoscrolls(true);
            desLabel1[i].setBounds(10,60,640, 340);
         //   desLabel1[i].setAlignmentY(TOP_ALIGNMENT);
            browseFile[i]=new JButton("Browse...");
            browseFile[i].setBounds(10, 400, 120, 25);
            fName[i]=new JLabel();
            fName[i].setBounds(140,400,250,25);
            submitButton[i]=new JButton("Submit");
            submitButton[i].setEnabled(false);
            submitButton[i].setBounds(400, 400,100, 25);
            status[i]=new JLabel();
            status[i].setFont(new Font("Serif",Font.BOLD,18));
            status[i].setBounds(500, 400, 150, 25);
           probPanel[i].add(probID[i]);
           probPanel[i].add(probID1[i]);
           probPanel[i].add(status[i]);
           probPanel[i].add(timeLabel[i]);
           probPanel[i].add(timeLabel1[i]);
          // probPanel[i].add(faltu);
           
           probPanel[i].add(pointLabel[i]);
           probPanel[i].add(pointLabel1[i]);
           probPanel[i].add(desLabel[i]);
           probPanel[i].add(desLabel1[i]);
           probPanel[i].add(browseFile[i]);
           probPanel[i].add(fName[i]);
           
           final int j=i;
           final int k=i;
           submitButton[i].addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        submitProblem(e,k);
                    } catch (IOException ex) {
                        Logger.getLogger(postLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
           browseFile[i].addActionListener(new ActionListener() {
                
                @Override
                public void actionPerformed(ActionEvent e) {
                browseFile(e,j);
                }
            });
           probPanel[i].add(submitButton[i]);
           
        }
          
    }
    private void submitProblem(ActionEvent e, int i) throws IOException
    {
        if(submitFile[i]!=null){
            try {
                String fileName=submitFile[i].getName();
                String ext=fileName.substring(fileName.lastIndexOf(".")+1,fileName.length());
        
                BufferedReader bufr=new BufferedReader(new FileReader(submitFile[i]));
                String arr[]=new String[7];
                arr[0]="submitProb";
                arr[1]=this.handle;
                System.out.println(arr[1]);
                arr[3]=probID1[i].getText();
                arr[4]=ext.toUpperCase();
                arr[5]="";
                String red;
                while((red=bufr.readLine())!=null){
                    arr[5]+=red+"\n";
                }
           //     System.out.println(arr[5]);
                String[] result=cl.establishConn(arr);
                status[i].setText(result[1]);
                if(!status[i].equals("Accepted"))
                {
                    status[i].setForeground(Color.GREEN);
                    submitButton[i].setEnabled(false);
                    browseFile[i].setEnabled(false);
                }
                else
                    status[i].setForeground(Color.RED);
                
                //   System.out.println(result[0]);
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(postLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void browseFile(ActionEvent e,int i)
    {
        try{
        JFileChooser jc=new JFileChooser();
        int ret=jc.showOpenDialog(probPanel[i]);
        if(ret==JFileChooser.APPROVE_OPTION)
        {
        submitFile[i]=jc.getSelectedFile();
        String fileName=submitFile[i].getName();
        String ext=fileName.substring(fileName.lastIndexOf(".")+1,fileName.length());
        String s1="c",s2="cpp";
        System.out.println(ext);
        if(ext.equals(s1)||ext.equals(s2))
        {
            fName[i].setText(fileName);
            submitButton[i].setEnabled(true);
        }
        else
        {
            fName[i].setText("Wrong File.");
        }
        }
        }
        catch(Exception ee)
        {
            System.out.println(ee);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

        //    public void run() {
               // new postLogin("Harsh",4,"eve").setVisible(true);
          //  }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    int prob;
    JPanel probPanel[];
    JLabel probID[];
    JLabel probID1[];
    JLabel timeLabel[];
    JLabel timeLabel1[];
    JLabel pointLabel[];
    JLabel pointLabel1[];
    JLabel desLabel[];
    JTextArea desLabel1[];
    JLabel pathLabel[];
    JButton browseFile[];
    JButton submitButton[];
    String handle;
    JLabel fName[];
    String eventid;
    Client cl;
    long remtime;
    File submitFile[];
    JLabel status[];
    
    
}
